export const initialPieces = [
  { rank: 'knight', position: 12, color: 'white', name: 'whiteKnight1' },
  { rank: 'knight', position: 17, color: 'white', name: 'whiteKnight2' },
  { rank: 'queen', position: 14, color: 'white', name: 'whiteQueen' },
  { rank: 'bishop', position: 13, color: 'white', name: 'whiteBishop1' },
  { rank: 'bishop', position: 16, color: 'white', name: 'whiteBishop2' },
  { rank: 'pawn', position: 24, color: 'white', name: 'whitePawn4' },
  { rank: 'pawn', position: 25, color: 'white', name: 'whitePawn5' },
  { rank: 'pawn', position: 26, color: 'white', name: 'whitePawn6' },
  { rank: 'pawn', position: 21, color: 'white', name: 'whitePawn1' },
  { rank: 'pawn', position: 22, color: 'white', name: 'whitePawn2' },
  { rank: 'pawn', position: 23, color: 'white', name: 'whitePawn3' },
  { rank: 'pawn', position: 27, color: 'white', name: 'whitePawn7' },
  { rank: 'pawn', position: 28, color: 'white', name: 'whitePawn8' },
  { rank: 'rook', position: 11, color: 'white', name: 'whiteRook1', ableToCastle: true },
  { rank: 'rook', position: 18, color: 'white', name: 'whiteRook2', ableToCastle: true },
  { rank: 'king', position: 15, color: 'white', name: 'whiteKing', ableToCastle: true },

  { rank: 'knight', position: 82, color: 'black', name: 'blackKnight1' },
  { rank: 'knight', position: 87, color: 'black', name: 'blackKnight2' },
  { rank: 'queen', position: 84, color: 'black', name: 'blackQueen' },
  { rank: 'bishop', position: 83, color: 'black', name: 'blackBishop1' },
  { rank: 'bishop', position: 86, color: 'black', name: 'blackBishop2' },
  { rank: 'pawn', position: 74, color: 'black', name: 'blackPawn4' },
  { rank: 'pawn', position: 75, color: 'black', name: 'blackPawn5' },
  { rank: 'pawn', position: 76, color: 'black', name: 'blackPawn6' },
  { rank: 'pawn', position: 71, color: 'black', name: 'blackPawn1' },
  { rank: 'pawn', position: 72, color: 'black', name: 'blackPawn2' },
  { rank: 'pawn', position: 73, color: 'black', name: 'blackPawn3' },
  { rank: 'pawn', position: 77, color: 'black', name: 'blackPawn7' },
  { rank: 'pawn', position: 78, color: 'black', name: 'blackPawn8' },
  { rank: 'rook', position: 81, color: 'black', name: 'blackRook1', ableToCastle: true },
  { rank: 'rook', position: 88, color: 'black', name: 'blackRook2', ableToCastle: true },
  { rank: 'king', position: 85, color: 'black', name: 'blackKing', ableToCastle: true }
];
